name: flutter_build

on:
  push:
    branches:
      - flutter
    tags:
      - v*

  pull_request:
    branches:
      - flutter

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 1'

jobs:
  desktop:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    name: desktop-${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install doit
        uses: awalsh128/cache-apt-pkgs-action@v1.4.2
        with:
          packages: python3-doit

      - name: Run analyzer
        run: doit analyze

      - name: Run tests
        run: doit test

  android:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    name: android-${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install doit
        uses: awalsh128/cache-apt-pkgs-action@v1.4.2
        with:
          packages: python3-doit

      - name: Build apk
        run: doit build:apk
